### ISSUE TITLE
async validate duplicate project codes on creation page

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#257] opened 2023-09-04 03:34 UTC
There's some other stuff we'd also like to validate as the user types:
- password rules
- project code

**Comment by rmunn** [comment] 2024-02-09 09:52
First observation: the project code is the final field on the form (well, after the language code, but it's auto-filled-in by the language code). So after filling it in, people are going to click "Create Project" next. So validating the project code asynchronously won't give the user any visible benefit if we do it on blur, because once the focus leaves that field, it's because they've just clicked on "Create Project".

I suggest moving the description down below the language code field. That way the user will fill in the language code, hit Tab or click on the next field, and start typing into the description textarea. While they type, the project code will be validated, and well before they're done filling in a description (unless they leave it empty), they'll see a green checkmark (or red X) by the project code.

**Comment by rmunn** [comment] 2024-02-09 10:03
The password rules part of this issue might be a duplicate of https://github.com/sillsdev/languageforge-lexbox/issues/57, so perhaps this issue should just be about the project-code rules, and #57 can be about the password-strength rules.

**Closed** 2024-02-15 13:45 UTC
Labels: UI Design
