### ISSUE TITLE
Annoyance: buttons on project page unresponsive until project history finishes loading

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#640] opened 2024-03-07 09:15 UTC
When you first load a project page, it looks like this:

![image](https://github.com/sillsdev/languageforge-lexbox/assets/90762/736b19b9-01c1-4bce-bc59-3fef2e81e359)

But the controls (the Add Members button, the Bulk Add Members button, the "More settings" dropdown) are unresponsive. Eventually the hgweb request finishes loading and displays a train-tracks graph, and then the buttons become responsive. This only happens on developer machines — in production the buttons are responsive even before the train-tracks graph has finished loading — so it's probably low priority. But it made me waste probably 30 minutes in total today, 5 seconds at a time, as I repeatedly loaded a test project page to test the "Bulk Add Members" button. So I'm creating this issue to keep track of the annoyance.

**Comment by hahn-kev** [comment] 2024-03-07 16:59
Is this not a hydration issue?

**Comment by myieye** [comment] 2024-03-27 10:20
I can't reproduce this on prod 🤔

**Comment by hahn-kev** [comment] 2024-08-07 07:49
@rmunn I can't reproduce this in prid now. Can you verify? close it if you can't reproduce it

**Comment by rmunn** [comment] 2024-08-23 07:02
Can still reproduce on local dev, but no on production. Can confirm that it's a hydration issue: on local dev, page doesn't hydrate until the browser has finished loading multiple .js files, whereas in production those are bundled so it takes a lot less time.

**Comment by rmunn** [comment] 2024-08-23 07:24
That is to say, I did manage to repro it in production once, when I managed to click quickly. But hydration takes so little time in production that it's not a serious issue. I'd still like to find a way to get faster hydration in local dev, but it's not actually a serious problem in prod.

**Comment by hahn-kev** [comment] 2024-08-27 03:25
did you throttle your connection when testing on prod? it might not be an issue for us with fast internet, but for people on a slower connection it's probably much more noticeable.

**Comment by rmunn** [comment] 2024-09-24 09:22
Probably relevant error from vite, visible in k8s logs but usually scrolls away too fast to notice:

[ui] viewer lexbox-dev: 9:20:49 AM [vite-plugin-svelte] /app/viewer/src/WebComponent.svelte svelte.preprocess depends on more than 10 external files which can cause slow builds and poor DX, try to reduce them. Found: /app/viewer/src/app.postcss, /app/viewer/src/lib/entry-editor/field.postcss, /app/viewer/src/app.d.ts, /app/viewer/src/main.ts, /app/viewer/src/vite-env.d.ts, /app/viewer/src/web-component.ts, /app/viewer/src/lib/config-data.ts, /app/viewer/src/lib/config-types.ts, /app/viewer/src/lib/debug.ts, /app/viewer/src/lib/entry-data.ts, /app/viewer/src/lib/i18n.ts, /app/viewer/src/lib/in-memory-api-service.ts, /app/viewer/src/lib/parts-of-speech.ts, /app/viewer/src/lib/semantic-domains.ts, /app/viewer/src/lib/utils.ts, /app/viewer/src/lib/writing-systems.ts, /app/viewer/src/lib/entry-editor/field-data.ts, /app/viewer/src/lib/entry-editor/view-data.ts, /app/viewer/src/lib/generated-signalr-client/Lexbox.ClientServer.Hubs.ts, /app/viewer/src/lib/mini-lcm/entry.ts, /app/viewer/src/lib/mini-lcm/example-sentence.ts, /app/viewer/src/lib/mini-lcm/i-entry.ts, /app/viewer/src/lib/mini-lcm/i-example-sentence.ts, /app/viewer/src/lib/mini-lcm/i-multi-string.ts, /app/viewer/src/lib/mini-lcm/i-sense.ts, /app/viewer/src/lib/mini-lcm/index.ts, /app/viewer/src/lib/mini-lcm/multi-string.ts, /app/viewer/src/lib/mini-lcm/part-of-speech.ts, /app/viewer/src/lib/mini-lcm/query-options.ts, /app/viewer/src/lib/mini-lcm/semantic-domain.ts, /app/viewer/src/lib/mini-lcm/sense.ts, /app/viewer/src/lib/mini-lcm/writing-system.ts, /app/viewer/src/lib/mini-lcm/writing-systems.ts, /app/viewer/src/lib/notifications/notifications.ts, /app/viewer/src/lib/services/event-bus.ts, /app/viewer/src/lib/services/lexbox-api.ts, /app/viewer/src/lib/services/option-provider.ts, /app/viewer/src/lib/services/save-event-service.ts, /app/viewer/src/lib/services/service-provider-dotnet.ts, /app/viewer/src/lib/services/service-provider-signalr.ts, /app/viewer/src/lib/services/service-provider.ts, /app/viewer/src/lib/services/view-service.ts, /app/viewer/src/lib/utils/search-params.ts, /app/viewer/src/lib/utils/size.ts, /app/viewer/src/lib/utils/style-fix.ts, /app/viewer/src/lib/utils/time.ts, /app/viewer/src/lib/generated-signalr-client/TypedSignalR.Client/Lexbox.ClientServer.Hubs.ts, /app/viewer/src/lib/generated-signalr-client/TypedSignalR.Client/index.ts, /app/viewer/src/App.svelte, /app/viewer/src/CrdtProjectView.svelte, /app/viewer/src/FwDataProjectView.svelte, /app/viewer/src/HomeView.svelte, /app/viewer/src/ProjectView.svelte, /app/viewer/src/TestProjectView.svelte, /app/viewer/src/lib/DictionaryEntry.svelte, /app/viewer/src/lib/Editor.svelte, /app/viewer/src/lib/activity/ActivityView.svelte, /app/viewer/src/lib/entry-editor/EntityListItemActions.svelte, /app/viewer/src/lib/entry-editor/FieldHelpIcon.svelte, /app/viewer/src/lib/entry-editor/FieldTitle.svelte, /app/viewer/src/lib/entry-editor/NewEntryDialog.svelte, /app/viewer/src/lib/history/HistoryView.svelte, /app/viewer/src/lib/layout/DevContent.svelte, /app/viewer/src/lib/layout/DictionaryEntryViewer.svelte, /app/viewer/src/lib/layout/EntryList.svelte, /app/viewer/src/lib/layout/FieldListDialog.svelte, /app/viewer/src/lib/layout/IndexCharacters.svelte, /app/viewer/src/lib/layout/Toc.svelte, /app/viewer/src/lib/layout/ViewOptionsDrawer.svelte, /app/viewer/src/lib/notifications/NotificationOutlet.svelte, /app/viewer/src/lib/sandbox/Sandbox.svelte, /app/viewer/src/lib/search-bar/SearchBar.svelte, /app/viewer/src/lib/status/SaveStatus.svelte, /app/viewer/src/lib/entry-editor/field-editors/FieldEditor.svelte, /app/viewer/src/lib/entry-editor/field-editors/MultiFieldEditor.svelte, /app/viewer/src/lib/entry-editor/field-editors/MultiOptionEditor.svelte, /app/viewer/src/lib/entry-editor/field-editors/SingleFieldEditor.svelte, /app/viewer/src/lib/entry-editor/field-editors/SingleOptionEditor.svelte, /app/viewer/src/lib/entry-editor/inputs/CrdtField.svelte, /app/viewer/src/lib/entry-editor/inputs/CrdtMultiOptionField.svelte, /app/viewer/src/lib/entry-editor/inputs/CrdtOptionField.svelte, /app/viewer/src/lib/entry-editor/inputs/CrdtTextField.svelte, /app/viewer/src/lib/entry-editor/object-editors/EntityEditor.svelte, /app/viewer/src/lib/entry-editor/object-editors/EntryEditor.svelte, /app/viewer/src/lib/entry-editor/object-editors/ExampleEditor.svelte, /app/viewer/src/lib/entry-editor/object-editors/SenseEditor.svelte, /app/viewer/tailwind.config.cjs

**Comment by rmunn** [comment] 2024-09-24 09:24
Although that's mostly for the viewer, and doesn't quite explain why `vite dev` takes so long to spin up for the lexbox UI. But this is probably part of why hydration takes so long: because vite is responding to some 50+ HTTP requests fetching each component individually. I wonder if there's a config option we could set to do some dev bundling?

**Closed** 2024-12-09 07:31 UTC
Labels: enhancement, Svelte, DX
