### ISSUE TITLE
Proposal: Switch to v7 GUIDs for primary keys

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#799] opened 2024-05-14 03:31 UTC
## Details

We are currently using v4 GUIDs as primary keys for most of our Postgres tables, but the new [v7 GUID format](https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-04.html#v7) has several advantages over v4:

* First 48 bits of the GUID are a timestamp (milliseconds since Unix epoch)
* Version field contains 7 (0b0111)
* Variant field contains 2 (0b10)
* 12 bits used for a counter that will increase monotonically if multiple v7 GUIDs are created in the same millisecond
* 62 bits of pseudorandom data at the end

The result is a GUID with unpredictable values (avoiding collisions), but which will be sequential with time, with GUIDs created later being guaranteed to come after GUIDs created earlier. This allows databases to be a lot more efficient with indexing.

## Proposed solution

I suggest that we start creating v7 GUIDs to use as database keys.

## Alternatives

Leave things as-is: our database isn't really large enough to notice the indexing inefficiencies inherent in v4 GUIDs used as primary keys.

## Additional notes

An unsigned 48-bit UNIX timestamp would wrap around in AD 10889, so there's no equivalent to the Y2038 issue.

There are several C# libraries designed for generating v7 GUIDs. I will not try to pick a favorite now, as by the time we get around to implementing this there might be community consensus around the best one, or there might be an official .NET API for creating v7 GUIDs.

**Comment by rmunn** [comment] 2024-05-14 03:34
Relevant API proposal in dotnet repo: https://www.github.com/dotnet/runtime/issues/88290

It's possible that EF Core may implement v7 GUIDs at some point (version 9.0?): https://www.github.com/dotnet/efcore/issues/30753

So it's possible that we won't need to do anything here.

**Comment by hahn-kev** [comment] 2024-05-14 15:59
There's also talk about this in the postgres repo for C# https://github.com/npgsql/efcore.pg/issues/2909

I don't really see the need to make this change on our own. If it gets merged into EF at some point we could take advantage of it, but I don't see the point. The main problem is index fragmentation leading to poor performance, but we don't really have that much data, so I'm not really concerned about performance that much. If at some point in the future we start to run into problems caused by using uuid v4 then we can take steps to mitigate the problem

**Closed** 2024-12-09 07:49 UTC
Labels: enhancement, engineering
