### ISSUE TITLE
ResizeObserver loop error

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#450] opened 2023-12-01 04:34 UTC
User had the following error:
https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-sveltekit-client/result/zUU6EBWULJG/trace/qtzGEe5456j?fields[]=s_name&fields[]=s_serviceName&span=ee4cf17b55e30411

![Image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/19ba35f7-f1f4-48ff-b707-f660fed279ca)

another issue is that the trace had no details about the error. At least we have the title in the dialog from the user, but that's also not good.

**Comment by rmunn** [comment] 2023-12-01 05:34
Confirmed, there's nothing using ResizeObserver in our code. It's possible this is being caused by something an extension is doing; I've come across [at least one case](https://stackoverflow.com/a/76190200) where a password manager was adding an autofill button into a field, which caused the field to resize in a way the page designer never considered, and this caused the error. I can't tell which browser the user is using, but I see an Adblock plugin icon in the top right of the screenshot; it's unlikely that AdBlock is causing the issue as nothing on Language Depot is serving ads, so Adblock shouldn't be rewriting any of the page. But it's worth asking the user if this happens every time, and if so whether it also happens with Adblock disabled.

**Comment by myieye** [comment] 2023-12-06 08:15
I was able to debug it with a user and tracked it to their LastPass extension (in Edge in this case). So, it's not really our problem.

```
web-client-content-script.js:2  DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at _s (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:125556)
    at Ou (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:138891)
    at t.unstable_runWithPriority (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:182589)
    at $o (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:83755)
    at Nu (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:136743)
    at vu (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:132867)
    at chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:84046
    at t.unstable_runWithPriority (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:182589)
    at $o (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:83755)
    at Jo (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:2:83991)
ss @ web-client-content-script.js:2
```

But we do have 3 problems:
1) For some reason the error message didn't make it on to the trace, so it was hard to find (it looks like the message we display is `event.message`, but we only trace `event.error`. So, that needs to change.)
2) We should include a stack trace in the trace. That will help us determine in the future if errors are coming from extensions, our own code, 3rd party libs etc.
3) How do we stop displaying meaningless errors like this one? Maybe we can just search for `chrome-extension://` in the stack trace and then maybe trace it, but not display it.

Hopefully we can install LastPass to reproduce this and then test and solve all 3 problems.

**Comment by rmunn** [comment] 2023-12-12 03:49
I've installed LastPass but haven't yet reproduced this, on either Firefox or Chromium (on Linux). I suspect from that error log that there might be a race condition between Svelte and LastPass which are both trying to modify the DOM: Svelte is tearing down the login page because it's rendering the home page instead, while LastPass is *also* trying to remove the `input` element because its extension decorated that element with a `style` attribute and hooked up events to it. To be certain of that theory I'd have to dig into the LastPass code, which I haven't done yet. But so far, with LastPass enabled, I haven't ever seen this error, even when actively resizing the window while logging in.

I'll continue trying to reproduce this, but if I can't reproduce it, we might have to close the issue for now.

**Closed** 2023-12-14 10:02 UTC
Labels: bug, Svelte, OpenTelemetry, User request, High Priority
