### ISSUE TITLE
There's no page loading feedback when clicking a link to navigate somewhere

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#197] opened 2023-07-26 05:35 UTC
On staging login as an admin, click on a project code. Nothing happens while the data is loading in the background to indicate that the page is loading, it just sits there. On a slow network connection this could be a while and users could get confused that it's broken

**Comment by myieye** [comment] 2024-01-18 15:31
Duplicate of #283

**Closed by myieye** 2024-01-18 15:31 UTC
Labels: UI Design
