### ISSUE TITLE
Show push/create project instructions if empty

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#688] opened 2024-04-03 07:15 UTC
This would replace the "Get project" button when the project is empty.

From Ann:

> I had a guy uploading a project to Language Depot.  He had trouble because he was using the instructions under the button to ‘Get Project’, which of course didn’t work.  He wanted to change those instructions, which would be wrong, but what do you think about a new button next to ‘Create Project’ that was titled something like ‘Upload new project’.  The steps he suggested are:
> 1. Download FLEx onto your computer.
> 2. Open the FLEx application and select "Create a new project...".
> 3. Fill in the required information: name of project, name for the folder (e.g. "Saluan-LOI"), etc. Then click "Finish".
> 4. After the new project opens, click on "Send/Receive\Send this Project for the first time".
> 5. Click on "OK (I have the master project)".
> 6. Click on "Settings..." and enter your LanguageDepot login credentials.
> 7. Click Log in, then select the Project ID from the drop-down menu.
> 8. Click on Internet. This will initiate the first Send/Receive.
> 
> Just passing this along.  It is documented elsewhere, but…

I would try to replace as much as possible with a link to FLEx instructions. Though we also need to remember that we're not only dealing with FLEx.

**Comment by hahn-kev** [comment] 2024-04-03 19:36
this feels like a duplicate of #686

**Comment by rmunn** [comment] 2024-04-12 04:47
Closing as duplicate of #686; will assign #686 high priority (and start working on it).

**Closed by rmunn** 2024-04-12 04:47 UTC
Labels: User request
